
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/my_security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=true&tinyInt1isBit=false
spring.datasource.username=root
spring.datasource.password=123456

logging.level.com.tuoheng=debug

server.servlet.session.timeout=10s

spring.mvc.servlet.load-on-startup=1

user.language
